### ISSUE TITLE
Update For Slate 0.25.x?

### ISSUE THREAD

**Issue by Slapbox** [GitbookIO/slate-trailing-block#3]
I looked at the code and I don't see why it doesn't work for 0.25.x, but it doesn't seem to.

Is it as simple as changing line 43 in `index.js`?

` transforms: {`

to

`changes: {`

Is it just no longer necessary in any way to use this plugin due to enter on void nodes producing a default node beneath them now?

**Comment by dmitrizzle** [comment]
This plugin is still required if you want to ensure a block at the end of your document. I'll submit a PR. Hopefully @SamyPesse can merge.

**Comment by Soreine** [comment]
Released v0.3.0
